#!/usr/bin/env python3
"""Master a burnable audio/data MIL-CD CDI for testers with CD-Rs.

senkosp2dreamcast's hardware-proven chain (its docs/kb/tooling.md §CDI
mastering: GDEMU rounds 1-5), at this port's geometry. A generic GDI->CDI
converter cannot work here: the shim streams the cart from a BAKED absolute
FAD as raw sectors past the filesystem, not a file. So the CD is mastered
fresh:

  session 1: silent audio track (cdi4dc)
  session 2: mode-2 data track at LBA 11702 = this script's ISO:
    11702..11717     IP.BIN -- CD-native, generated by mkdcdisc, branded like
                     the GDI. NOT the GD donor's: a retail GD IP.BIN dies on
                     a real CD boot (license -> ~6 s black -> reboot) while
                     Flycast lets it through (senko HW round 4 A/B).
    ..+FS_SECTORS    ISO9660 (mkisofs -C 0,11702) holding the SCRAMBLED
                     1ST_READ.BIN -- the boot ROM descrambles it on CD media,
                     loads it plain on GD (senko cdi/boot-smoke A/B legs) --
                     zero-padded to the fixed region
    13494..          the cart image, raw (the shim's FAD reads, not a file)

CART_FAD on CD = 150 + 11702 + FS_SECTORS = 13644 (Makefile CD_CART_FAD,
baked into shim + loader by `make cdi`). The loader passed in MUST be that
build: this script refuses one without the CD-FAD marks. Always build via
`make cdi`.
"""
import argparse, pathlib, sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import make_gdi   # IP branding constants, iplogo, donor cache, CART_SIZE, run

SECTOR = 2048
SESSION2_LBA = 11702        # cdi4dc's audio/data session-2 start (= mkdcdisc -M)
FS_SECTORS = 1792           # IP+FS+loader region; loader is ~430 sectors today
CART_FAD_CD = 150 + SESSION2_LBA + FS_SECTORS   # 13644, keep = Makefile CD_CART_FAD
CDI4DC = pathlib.Path("tools/img4dc/build/cdi4dc/cdi4dc")
MKDCDISC = pathlib.Path("tools/mkdcdisc/build/mkdcdisc")
SCRAMBLE = pathlib.Path("tools/kos/utils/scramble/scramble")

README = """\
CLEOPATRA FORTUNE PLUS -- Dreamcast port, CD-R (CDI) build
==========================================================

cleopatra.cdi is a self-booting audio/data MIL-CD image. Burn it as a
DISC IMAGE with a CDI-aware burner (Padus DiscJuggler, Alcohol 120%,
ImgBurn via a converter); do not extract it or burn its contents as
files. Older Dreamcast lasers like slow burns: 8x or lower on a quality
CD-R.

Late-2000+ Dreamcasts that block MIL-CD cannot boot any burned CD --
that is the console, not the disc. GDEMU/ODE users: use the [GDI]
release instead (faster loads, the hardware-tested path).

Reset: A+B+X+Y+Start on either pad reboots the console.

This CDI is newer than the GDI -- if the disc fails to boot or dies
mid-game where the GDI works, please report it.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", default="Cleopatra Fortune Plus.dat")
    ap.add_argument("--loader", default="build/1ST_READ.BIN")
    ap.add_argument("--out", default="build/cdi")
    a = ap.parse_args()
    out = pathlib.Path(a.out); out.mkdir(parents=True, exist_ok=True)
    for t in (CDI4DC, MKDCDISC, SCRAMBLE):
        assert t.exists(), f"{t} missing -- docs/kb/tooling.md §CDI mastering"

    ldr = pathlib.Path(a.loader).read_bytes()
    # the embedded shim's mark; the loader's own CART_FAD self-checks at boot
    # (it halts red unless it reads the NAOMI header there)
    marks = make_gdi.cdi_marks(ldr)
    assert marks == [CART_FAD_CD], \
        f"loader CDI marks {marks} != [{CART_FAD_CD}] -- build via `make cdi`"
    rom = pathlib.Path(a.rom).read_bytes()
    assert len(rom) == make_gdi.CART_SIZE, f"cart size {len(rom):#x} != {make_gdi.CART_SIZE:#x}"

    # IP.BIN: mkdcdisc's CD bootstrap, branded with the GDI's fields + MR logo;
    # peripherals copied from the donor (the GDI's), area stays mkdcdisc's JUE.
    # -I dumps the data track ISO, whose first 16 sectors are the IP.
    donor_ip = (make_gdi.donor_tracks(pathlib.Path("build")) / "track03.iso").read_bytes()[:256]
    ipgen = out / "ipgen.cdi"
    cmd = [str(MKDCDISC), "-q", "--allow-overwrite", "-b", a.loader, "-o", str(ipgen), "-I",
           "-n", make_gdi.IP_TITLE, "-a", make_gdi.IP_COMPANY, "-s", make_gdi.IP_PRODUCT,
           "-P", make_gdi.IP_VERSION, "-r", make_gdi.IP_DATE,
           "-H", donor_ip[0x38:0x40].decode().strip()]
    if make_gdi.IPLOGO_MR.exists():
        cmd += ["-i", str(make_gdi.IPLOGO_MR)]
    else:
        print("note: iplogo.mr absent -> mkdcdisc's stock license screen")
    make_gdi.run(cmd)
    ip = ipgen.with_suffix(".iso").read_bytes()[:16 * SECTOR]
    ipgen.unlink(); ipgen.with_suffix(".iso").unlink()
    assert ip[0x25:0x2E] == b"CD-ROM1/1", "mkdcdisc IP device string moved?"
    assert ip[0x80:0x80 + len(make_gdi.IP_TITLE)] == make_gdi.IP_TITLE.encode()
    (out / "ip.bin").write_bytes(ip)

    # FS region: scrambled 1ST_READ.BIN as the only file, IP as the system
    # area, extents absolute from LBA 11702. -no-pad: mkisofs's 150-sector
    # zero tail is redundant (we pad to FS_SECTORS ourselves).
    fsroot = out / "fsroot"; fsroot.mkdir(exist_ok=True)
    make_gdi.run([str(SCRAMBLE), a.loader, str(fsroot / "1ST_READ.BIN")])
    base = out / "base.iso"
    make_gdi.run(["mkisofs", "-quiet", "-no-pad", "-iso-level", "1", "-V", "CLEOPATRA",
                  "-C", f"0,{SESSION2_LBA}", "-G", str(out / "ip.bin"),
                  "-o", str(base), str(fsroot)])
    fs = base.read_bytes()
    base.unlink()
    assert len(fs) <= FS_SECTORS * SECTOR, f"FS+loader {len(fs)} B exceeds {FS_SECTORS} sectors"

    iso = out / "disc.iso"
    with open(iso, "wb") as f:
        f.write(fs)
        f.write(b"\0" * (FS_SECTORS * SECTOR - len(fs)))
        f.write(rom)
    make_gdi.run([str(CDI4DC), str(iso), str(out / "cleopatra.cdi")])
    iso.unlink()   # 113 MB intermediate; the .cdi is the artifact
    (out / "README.txt").write_text(README)
    print(f"OK {out}/cleopatra.cdi (audio/data MIL-CD: data track at LBA {SESSION2_LBA}, "
          f"cart at FAD {CART_FAD_CD})")


if __name__ == "__main__":
    main()
